import React from 'react';

const DisclaimerPolicyContent = () => (
  <div className="px-5 max-h-[500px] overflow-y-auto">
    <h2 className="text-center font-bold text-red-450 mb-5">
      PRIVATE AND CONFIDENTIAL - FOR CLIENT USE AND DISCUSSION ONLY
    </h2>
    <h2 className="text-center font-bold mb-5 border-b border-black">DISCLAIMER POLICY</h2>
    <p className="mb-5">
      We try to keep the <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> up and
      running and free of annoyances. But we make no promises that we will succeed.
    </p>

    <p className="mb-5 font-medium">
      THE <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> IS PROVIDED “AS IS” AND
      “AS AVAILABLE” AND TO THE EXTENT PERMITTED BY LAW WITHOUT WARRANTIES OF ANY KIND, EITHER
      EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES FOR A PARTICULAR
      PURPOSE, TITLE, AND NON-INFRINGEMENT. IN ADDITION, WHILE COMPANY ATTEMPTS TO PROVIDE A GOOD
      USER EXPERIENCE, WE DO NOT REPRESENT OR WARRANT THAT: (A) THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> WILL ALWAYS BE SECURE,
      ERROR-FREE, (B) THE <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> WILL
      ALWAYS FUNCTION WITHOUT DELAYS, DISRUPTIONS, OR IMPERFECTIONS; OR (C) THAT ANY CONTENT, USER
      CONTENT, OR INFORMATION YOU OBTAIN ON OR THROUGH THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> WILL BE TIMELY OR ACCURATE.
    </p>

    <p className="mb-5 font-medium">
      YOU UNDERSTAND AND AGREE THAT YOU MAY BE EXPOSED TO CONTENT THAT MIGHT BE OFFENSIVE, ILLEGAL,
      MISLEADING, OR OTHERWISE INAPPROPRIATE, NONE OF WHICH COMPANY WILL BE RESPONSIBLE FOR. THE
      COMPANY WILL NOT BE RESPONSIBLE FOR ANY DAMAGE SUFFERED BY USERS FROM USE OF THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> PROVIDED ON THE SERVICES
      AVAILABLE ON THE <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> OR THE
      CONTENT ON THIS <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span>. THIS INCLUDES
      BUT IS NOT LIMITED TO, LOSS OF REVENUE/DATA RESULTING FROM DELAYS, AS MAY OCCUR BECAUSE OF ANY
      ACT/OMISSION OF PARTIES.
    </p>

    <p className="mb-5 font-medium">
      THIS DISCLAIMER OF LIABILITY ALSO APPLIES TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF
      PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR
      TRANSMISSION, COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED
      ACCESS TO, ALTERATION OF, OR USE OF RECORD, WHETHER FOR BREACH OF CONTRACT, TORTUOUS
      BEHAVIOUR, NEGLIGENCE, OR UNDER ANY OTHER CAUSE OF ACTION.
    </p>

    <p className="mb-5 font-medium">
      THE COMPANY ALSO MAKES IT CLEAR THAT IT SHALL NOT BE HELD LIABLE FOR ANY
      DAMAGE/HURT/INCONVENIENCE CAUSED TO THE USER THROUGH THE COURSE OF USAGE OF THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> AND/OR CONTENT OR AS A RESULT
      OF THE USERS’ ACTIONS. THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF
      THE USERS.
    </p>

    <p className="mb-5 font-medium">
      THE CONTENT ON THE <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> ARE
      INTENDED TO BE SUBJECT TO AVAILABILITY, WITHOUT ANY PROMISES OR GUARANTEES ON THE SAME BY THE
      COMPANY OR BY THE WEBSITE & <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span>,
      AND WHILE CERTAIN INFORMATION AVAILABLE ON THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> IS THE PROPERTY OF THE COMPANY
      AND THE COMPANY ENDEAVOURS TO KEEP THE SAID INFORMATION UPDATED AND ACCURATE, THE COMPANY
      SHALL NOT MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ABOUT THE
      COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY OR AVAILABILITY WITH RESPECT TO THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> OR
    </p>

    <p className="mb-5 font-medium">
      THE INFORMATION, OR RELATED GRAPHICS CONTAINED ON THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> FOR ANY PURPOSE. ANY RELIANCE
      YOU PLACE ON SUCH INFORMATION IS THEREFORE STRICTLY AT YOUR OWN RISK.
    </p>

    <p className="mb-5 font-medium">
      THE COMPANY BEARS NO RESPONSIBILITY WHATSOEVER FOR ANY CONSEQUENCES ARISING FROM THE USE OF
      THE <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> BY USERS. THE USE OF THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> ARE THE SOLE RESPONSIBILITY OF
      THE USER (OR LEGALLY AUTHORIZED PERSON ON BEHALF OF THE USER), AND IN CASE OF ANY NEGLIGENCE
      ON THE PART OF THE USER IN ACTING ON THE SAME SHALL NOT BE CONSTRUED AS IMPOSING ANY
      LIABILITY, DIRECT OR INDIRECT, ON THE COMPANY/APPLICATION AND/OR WEBSITE.
    </p>

    <p className="mb-5 font-medium">
      THE COMPANY SHALL DISCLAIM ALL RESPONSIBILITY AND OWNS NO LIABILITY TO USERS FOR ANY OUTCOME
      (INCIDENTAL, DIRECT, INDIRECT OR OTHERWISE) FROM THE USE OF THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE.</span> IN NO EVENT WILL THE COMPANY
      BE LIABLE FOR ANY LOSS OR DAMAGE INCLUDING WITHOUT LIMITATION, INDIRECT OR CONSEQUENTIAL LOSS
      OR DAMAGE, OR ANY LOSS OR DAMAGE WHATSOEVER ARISING FROM LOSS OF DATA OR PROFITS ARISING OUT
      OF, OR IN CONNECTION WITH, THE USE OF THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE.</span>
    </p>

    <p className="mb-5 font-medium">
      THROUGH THIS <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span>, YOU ARE ABLE TO
      LINK TO OTHER <span className="bg-gray-200">APPLICATION AND/OR WEBSITES</span> WHICH ARE NOT
      UNDER THE CONTROL OF THE COMPANY. WE HAVE NO CONTROL OVER NATURE, CONTENT AND AVAILABILITY OF
      THOSE SITES. THE INCLUSION OF ANY LINKS DOES NOT NECESSARILY IMPLY A RECOMMENDATION OR ENDORSE
      THE VIEWS EXPRESSED WITHIN THEM. EVERY EFFORT IS MADE TO KEEP THE
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> UP AND RUNNING SMOOTHLY.
      HOWEVER, THE COMPANY TAKES NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE FOR, THE{' '}
      <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> BEING TEMPORARILY UNAVAILABLE
      DUE TO TECHNICAL ISSUES BEYOND OUR CONTROL.
    </p>

    <p className="mb-5 font-medium">
      TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY WILL HAVE NO LIABILITY RELATED
      TO USER CONTENT ARISING UNDER INTELLECTUAL PROPERTY RIGHTS, LIBEL, PRIVACY, PUBLICITY,
      OBSCENITY OR OTHER LAWS. <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> ALSO
      DISCLAIMS ALL LIABILITY WITH RESPECT TO THE MISUSE, LOSS, MODIFICATION OR UNAVAILABILITY OF
      ANY USER CONTENT.
    </p>

    <p className="mb-5 font-medium">
      THE USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED
      THROUGH THE <span className="bg-gray-200">APPLICATION AND/OR WEBSITE</span> ARE DONE ENTIRELY
      AT HIS/HER OWN DISCRETION AND RISK AND HE/SHE WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO
      HIS/HER COMPUTER SYSTEMS OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR
      DATA.
    </p>
  </div>
);

export default DisclaimerPolicyContent;
