// TODO: remove eslint after adding more
// eslint-disable-next-line import/prefer-default-export
export const smtpSupportedServices = [
  { label: '1und1', value: '1und1' },
  { label: 'AOL', value: 'AOL' },
  { label: 'DebugMail.io', value: 'DebugMail.io' },
  { label: 'DynectEmail', value: 'DynectEmail' },
  { label: 'FastMail', value: 'FastMail' },
  { label: 'GandiMail', value: 'GandiMail' },
  { label: 'Gmail', value: 'Gmail' },
  { label: 'Godaddy', value: 'Godaddy' },
  { label: 'GodaddyAsia', value: 'GodaddyAsia' },
  { label: 'GodaddyEurope', value: 'GodaddyEurope' },
  { label: 'hot.ee', value: 'hot.ee' },
  { label: 'Hotmail', value: 'Hotmail' },
  { label: 'iCloud', value: 'iCloud' },
  { label: 'mail.ee', value: 'mail.ee' },
  { label: 'Mail.ru', value: 'Mail.ru' },
  { label: 'Mailgun', value: 'Mailgun' },
  { label: 'Mailjet', value: 'Mailjet' },
  { label: 'Mandrill', value: 'Mandrill' },
  { label: 'Naver', value: 'Naver' },
  { label: 'Postmark', value: 'Postmark' },
  { label: 'QQ', value: 'QQ' },
  { label: 'QQex', value: 'QQex' },
  { label: 'SendCloud', value: 'SendCloud' },
  { label: 'SendGrid', value: 'SendGrid' },
  { label: 'SES', value: 'SES' },
  { label: 'Sparkpost', value: 'Sparkpost' },
  { label: 'Yahoo', value: 'Yahoo' },
  { label: 'Yandex', value: 'Yandex' },
  { label: 'Zoho', value: 'Zoho' },
  { label: 'Others', value: 'others' },
];
